[package]
name = "dipstick-can"
version = "0.1.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
dipstick-core.workspace = true
dipstick-proto.workspace = true
futures.workspace = true
socketcan.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
