[workspace]
members = ["packages/*"]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/workspaces.html

[workspace.package]
authors = ["Simon Berger <simon.berger@inomotech.com>"]
edition = "2021"
homepage = "https://github.com/inomotech-foss/dipstick"
repository = "https://github.com/inomotech-foss/dipstick"
rust-version = "1.76"

[workspace.dependencies]
dipstick-proto = { path = "packages/dipstick-proto" }

anyhow = "1.0.80"
async-trait = "0.1.77"
futures = "0.3.30"
prost = "0.12.3"
prost-types = "0.12.3"
protoc-wkt = "1.0.0+3.20.1"
tokio = { version = "1.36.0", features = ["full"] }
tonic = "0.11.0"
tonic-reflection = "0.11.0"
tonic-web = "0.11.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[profile.release]
lto = true
