[workspace]
members = ["packages/*"]
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/workspaces.html

[workspace.package]
authors = ["Simon Berger <simon.berger@inomotech.com>"]
edition = "2021"
homepage = "https://github.com/inomotech-foss/dipstick"
repository = "https://github.com/inomotech-foss/dipstick"
rust-version = "1.76"

[workspace.dependencies]
dipstick-proto = { path = "packages/dipstick-proto" }

anyhow = "1"
async-trait = "0.1"
futures = "0.3"
prost = "0.12"
prost-types = "0.12"
protoc-wkt = "1"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["full"] }
tonic = "0.11"
tonic-reflection = "0.11"
tonic-web = "0.11"
tracing = "0.1"
tracing-subscriber = "0.3"

[profile.release]
lto = true
