// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "dipstick/device/v1/sensor.proto" (package "dipstick.device.v1", syntax proto3)
// tslint:disable
import { Value } from "../../../google/protobuf/struct";
import { Timestamp } from "../../../google/protobuf/timestamp";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";

/**
 * @generated from protobuf message dipstick.device.v1.SensorStatus
 */
export interface SensorStatus {
  /**
   * @generated from protobuf field: google.protobuf.Timestamp timestamp = 1;
   */
  timestamp?: Timestamp;
  /**
   * @generated from protobuf field: string unit = 3;
   */
  unit: string;
  /**
   * @generated from protobuf field: google.protobuf.Value value = 2;
   */
  value?: Value;
}
/**
 * @generated from protobuf message dipstick.device.v1.SensorEvent
 */
export interface SensorEvent {
  /**
   * @generated from protobuf field: google.protobuf.Timestamp timestamp = 1;
   */
  timestamp?: Timestamp;
  /**
   * @generated from protobuf field: string sensor = 2;
   */
  sensor: string;
  /**
   * @generated from protobuf field: google.protobuf.Value value = 3;
   */
  value?: Value;
}
// @generated message type with reflection information, may provide speed optimized methods
class SensorStatus$Type extends MessageType<SensorStatus> {
  constructor() {
    super("dipstick.device.v1.SensorStatus", [
      { no: 1, name: "timestamp", kind: "message", T: () => Timestamp },
      { no: 3, name: "unit", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      { no: 2, name: "value", kind: "message", T: () => Value },
    ]);
  }
  create(value?: PartialMessage<SensorStatus>): SensorStatus {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.unit = "";
    if (value !== undefined)
      reflectionMergePartial<SensorStatus>(this, message, value);
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: SensorStatus,
  ): SensorStatus {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* google.protobuf.Timestamp timestamp */ 1:
          message.timestamp = Timestamp.internalBinaryRead(
            reader,
            reader.uint32(),
            options,
            message.timestamp,
          );
          break;
        case /* string unit */ 3:
          message.unit = reader.string();
          break;
        case /* google.protobuf.Value value */ 2:
          message.value = Value.internalBinaryRead(
            reader,
            reader.uint32(),
            options,
            message.value,
          );
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw")
            throw new globalThis.Error(
              `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
            );
          let d = reader.skip(wireType);
          if (u !== false)
            (u === true ? UnknownFieldHandler.onRead : u)(
              this.typeName,
              message,
              fieldNo,
              wireType,
              d,
            );
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: SensorStatus,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* google.protobuf.Timestamp timestamp = 1; */
    if (message.timestamp)
      Timestamp.internalBinaryWrite(
        message.timestamp,
        writer.tag(1, WireType.LengthDelimited).fork(),
        options,
      ).join();
    /* string unit = 3; */
    if (message.unit !== "")
      writer.tag(3, WireType.LengthDelimited).string(message.unit);
    /* google.protobuf.Value value = 2; */
    if (message.value)
      Value.internalBinaryWrite(
        message.value,
        writer.tag(2, WireType.LengthDelimited).fork(),
        options,
      ).join();
    let u = options.writeUnknownFields;
    if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(
        this.typeName,
        message,
        writer,
      );
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message dipstick.device.v1.SensorStatus
 */
export const SensorStatus = new SensorStatus$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SensorEvent$Type extends MessageType<SensorEvent> {
  constructor() {
    super("dipstick.device.v1.SensorEvent", [
      { no: 1, name: "timestamp", kind: "message", T: () => Timestamp },
      { no: 2, name: "sensor", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
      { no: 3, name: "value", kind: "message", T: () => Value },
    ]);
  }
  create(value?: PartialMessage<SensorEvent>): SensorEvent {
    const message = globalThis.Object.create(this.messagePrototype!);
    message.sensor = "";
    if (value !== undefined)
      reflectionMergePartial<SensorEvent>(this, message, value);
    return message;
  }
  internalBinaryRead(
    reader: IBinaryReader,
    length: number,
    options: BinaryReadOptions,
    target?: SensorEvent,
  ): SensorEvent {
    let message = target ?? this.create(),
      end = reader.pos + length;
    while (reader.pos < end) {
      let [fieldNo, wireType] = reader.tag();
      switch (fieldNo) {
        case /* google.protobuf.Timestamp timestamp */ 1:
          message.timestamp = Timestamp.internalBinaryRead(
            reader,
            reader.uint32(),
            options,
            message.timestamp,
          );
          break;
        case /* string sensor */ 2:
          message.sensor = reader.string();
          break;
        case /* google.protobuf.Value value */ 3:
          message.value = Value.internalBinaryRead(
            reader,
            reader.uint32(),
            options,
            message.value,
          );
          break;
        default:
          let u = options.readUnknownField;
          if (u === "throw")
            throw new globalThis.Error(
              `Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`,
            );
          let d = reader.skip(wireType);
          if (u !== false)
            (u === true ? UnknownFieldHandler.onRead : u)(
              this.typeName,
              message,
              fieldNo,
              wireType,
              d,
            );
      }
    }
    return message;
  }
  internalBinaryWrite(
    message: SensorEvent,
    writer: IBinaryWriter,
    options: BinaryWriteOptions,
  ): IBinaryWriter {
    /* google.protobuf.Timestamp timestamp = 1; */
    if (message.timestamp)
      Timestamp.internalBinaryWrite(
        message.timestamp,
        writer.tag(1, WireType.LengthDelimited).fork(),
        options,
      ).join();
    /* string sensor = 2; */
    if (message.sensor !== "")
      writer.tag(2, WireType.LengthDelimited).string(message.sensor);
    /* google.protobuf.Value value = 3; */
    if (message.value)
      Value.internalBinaryWrite(
        message.value,
        writer.tag(3, WireType.LengthDelimited).fork(),
        options,
      ).join();
    let u = options.writeUnknownFields;
    if (u !== false)
      (u == true ? UnknownFieldHandler.onWrite : u)(
        this.typeName,
        message,
        writer,
      );
    return writer;
  }
}
/**
 * @generated MessageType for protobuf message dipstick.device.v1.SensorEvent
 */
export const SensorEvent = new SensorEvent$Type();
