[package]
name = "dipstick-proto"
version = "0.1.0"
publish = false

authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes.workspace = true
prost-types.workspace = true
prost.workspace = true
protoc-wkt.workspace = true
tonic.workspace = true
