[package]
name = "dipstick"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.deb]
maintainer-scripts = "debian/"
systemd-units = { enable = true }

[dependencies]
anyhow.workspace = true
bytes.workspace = true
dipstick-can.workspace = true
dipstick-core.workspace = true
dipstick-device.workspace = true
dipstick-gpio.workspace = true
dipstick-proto.workspace = true
dipstick-shadow.workspace = true
dipstick-spi.workspace = true
dipstick-stack.workspace = true
dipstick-xcp.workspace = true
futures.workspace = true
rand.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tonic-reflection.workspace = true
tonic-web.workspace = true
tonic.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
