[package]
name = "dipstick-core"
version = "0.1.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
console-subscriber.workspace = true
dipstick-proto.workspace = true
futures.workspace = true
percent-encoding.workspace = true
rand.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
