[package]
name = "dipstick-gpio"
version = "0.2.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
dipstick-core.workspace = true
dipstick-proto.workspace = true
futures.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
tokio-util.workspace = true
tokio-stream.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
gpiocdev.workspace = true
